### ISSUE TITLE
Missing Class 390 and Class 185 (v1.3.4 via In-game Browser)

### ISSUE THREAD

**Issue by fagank-y21** [StarRaid/Representitive-UK-Trainset#6]
Hi there, not really sure where the right place to ask is but thought I'd mention here. I've been going over my GRF collection, getting rid of ones I don't use and while cleaning out the other train sets since this is my favourite ended up finding the repo. When checking that I had the latest version I noticed that with both the 1.3.3 release on Github and the 1.3.4 from the in-game browser the Class 390 was missing. Even with show hidden enabled just in case and extended train library selected nothing. The Class 210 and Class 370 are avalaible but even if I set the year to 2006, 2010 or 2020 the Class 390 is missing. In addition I checked the commits and it appeared that the Class 185 was added (please do correct if wrong) and that was missing as well after deleting the GitHub Release and downloading the latest one in game. 370 was also in that one and no 390.

I've got some screenshots showing my current configuration though if there are any other settings I should try let me know. I'm running the Steam Release of OpenTTD 12.2 and the screenshots are from brand new games.

![20221216230607_1](https://user-images.githubusercontent.com/11998940/208204371-f6486d60-79f2-4ffd-bead-f9b55db0e72b.jpg)
2010 New Game - No Class 185 or Class 390

![20221216230747_1](https://user-images.githubusercontent.com/11998940/208204374-842c75f3-79f7-4e8b-b3d2-6d29c19c9eae.jpg)
1984 New Game - Class 370 is avaliable from v1.3.3 and Class 210 v1.3.2

![20221216230858_1](https://user-images.githubusercontent.com/11998940/208204377-9dfc98cf-857c-48a8-9333-5ccda10131ed.jpg)
Parameters used throughout

**Comment by StarRaid** [comment]
Thank you for the feedback! I have checked the code for the 390 and it was using the incorrect railtype label, so upon next release it will show up again in vanilla games. For now I would recommend using a track set like SUKTS or U&ReRMM 2 as I tested the same version of RUKTS with these track sets and the issue was not present. 

As for the 185, it isn't actually coded into the GRF yet, but has some sprites drawn. It isn't ready to be released yet.
I hope this clears some things up.
